### ISSUE TITLE
Bioconda recipe

### ISSUE THREAD

**Issue by matthdsm** [ExaScience/elprep#11]
Hi,

Following your talk at FOSDEM earlier this week, I've taken the liberty of creating a conda recipe for elPrep. I believe this will add another layer of visibility to the tool, and make it even easier to install.
Please feel free to modify/update/whatever.

https://github.com/bioconda/bioconda-recipes/pull/7576

Cheers
Matthias

**Comment by pcostanza** [comment]
Thanks a lot indeed, this is highly appreciated!

Best,
Pascal
