### ISSUE TITLE
python script handing of `single-end` flag

### ISSUE THREAD

**Issue by matthdsm** [ExaScience/elprep#15]
Hi,

when running the following command:
```
elprep-sfm-gnupar.py \
       elprep_sWGS.bam \
        elprep_sWGS_filtered.bam \
        --mark-duplicates \
        --sorting-order coordinate\
        --nr-of-threads $CORES \
        --nr-of-jobs 2 \
        --intermediate-files-output-type sam \
        --intermediate-files-output-prefix elprep \
        --single-end
```
I get the following error when the filter step is about to start:
```
flag provided but not defined: -single-end
```

It seems to me the sfm scripts do nog handle the `--single-end` flag correctly by passing it to the filter command, resulting in the error above.

Could you have a look at those?

Thanks
M

**Comment by caherzee** [comment]
Hi Matthias,

If you move the --single-end option to the front, the problem should not occur. So rather:

elprep-sfm-gnupar.py input.bam output.bam --single-end ....

There seems to be some problem in the Python script if it is the last option. We will fix this later.

Thanks!

**Comment by matthdsm** [comment]
Hi Charlotte,

Thanks!
M
