### ISSUE TITLE
sfm sorting problem

### ISSUE THREAD

**Issue by geertvandeweyer** [ExaScience/elprep#18]
elprep v 4.0.1 SFM functionality results in incorrectly sorted bam. 

`command : /opt/NGS/binaries/elPrep/4.0.1/elprep sfm 'DNA1802266B_recalibrated.bam' /home/shared_data_medgen_frax/Exome_CNV_TestRuns/CNV_tmp_files/dna1802266b/dna1802266b.full.bam --remove-duplicates --filter-mapping-quality '40' --log-path '/home/shared_data_medgen_frax/Exome_CNV_TestRuns/CNV_Job_Output/dna1802266b/' --filter-unmapped-reads --nr-of-threads '16' --sorting-order 'coordinate' --filter-non-overlapping-reads '/opt/NGS/References/hg19/BedFiles/WGS.bed' --replace-reference-sequences '/opt/NGS/References/hg19_masked_par/samtools/0.1.19/hg19.dict' `

results in error when applying `samtools index resulting.bam`

`[bam_index_core] the alignment is not sorted (ST-K00127:290:HNFYKBBXX:1:1216:29904:8330): 249240352 > 752696 in 2-th chr
[bam_index_build2] fail to index the BAM file.`

running elprep filter instead of elprep sfm results in correct sorting, so the problem seems to be related to the SFM merging. I also tried with --contig-group-size 1, instead of default, with similar errors as a result.

**Comment by pcostanza** [comment]
Charlotte and I just discussed this bug, and we have a hunch why this might happen. Could you double-check the following for us, if it's not a big hassle?

Could you first run the following:

elprep filter input.bam output.bam --replace-reference-sequences hg19.dict --sorting-order unknown

and then the rest of the pipeline with elprep sfm but without --replace-reference-sequences

It's important that the first call uses elprep filter, not elprep sfm.

If this 'fixes' the problem, then we have a pretty good idea what causes it.

Thanks a lot,
Pascal

**Comment by geertvandeweyer** [comment]
Ok, I'll run it overnightSent from my Huawei Mobile-------- Original Message --------Subject: Re: [ExaScience/elprep] sfm sorting problem (#18)From: Pascal Costanza To: ExaScience/elprep CC: geertvandeweyer ,Author Charlotte and I just discussed this bug, and we have a hunch why this might happen. Could you double-check the following for us, if it's not a big hassle?
Could you first run the following:
elprep filter input.bam output.bam --replace-reference-sequences hg19.dict --sorting-order unknown
and then the rest of the pipeline with elprep sfm but without --replace-reference-sequences
It's important that the first call uses elprep filter, not elprep sfm.
If this 'fixes' the problem, then we have a pretty good idea what causes it.
Thanks a lot,
Pascal

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/ExaScience/elprep","title":"ExaScience/elprep","subtitle":"GitHub repository","main_image_url":"https://github.githubassets.com/images/email/message_cards/header.png","avatar_image_url":"https://github.githubassets.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/ExaScience/elprep"}},"updates":{"snippets":[{"icon":"PERSON","message":"@pcostanza in #18: Charlotte and I just discussed this bug, and we have a hunch why this might happen. Could you double-check the following for us, if it's not a big hassle?\r\n\r\nCould you first run the following:\r\n\r\nelprep filter input.bam output.bam --replace-reference-sequences hg19.dict --sorting-order unknown\r\n\r\nand then the rest of the pipeline with elprep sfm but without --replace-reference-sequences\r\n\r\nIt's important that the first call uses elprep filter, not elprep sfm.\r\n\r\nIf this 'fixes' the problem, then we have a pretty good idea what causes it.\r\n\r\nThanks a lot,\r\nPascal\r\n"}],"action":{"name":"View Issue","url":"https://github.com/ExaScience/elprep/issues/18#issuecomment-456412512"}}}
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/ExaScience/elprep/issues/18#issuecomment-456412512",
"url": "https://github.com/ExaScience/elprep/issues/18#issuecomment-456412512",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by geertvandeweyer** [comment]
Your suggestion worked. The following commands were run, resulting in a correct indexing afterwards:

`/opt/NGS/binaries/elPrep/4.0.1/elprep filter 'DNA1802266B_recalibrated.bam' '/tmp/dna1802266b.full.bam' --nr-of-threads '16' --sorting-order 'unknown' --replace-reference-sequences '/opt/NGS/References/hg19_masked_par/samtools/0.1.19/hg19.dict'`

`/opt/NGS/binaries/elPrep/4.0.1/elprep sfm '/tmp/dna1802266b.full.bam' /home/shared_data_medgen_frax/Exome_CNV_TestRuns/CNV_tmp_files/dna1802266b/dna1802266b.full.bam --remove-duplicates --filter-mapping-quality '40' --log-path '/home/shared_data_medgen_frax/Exome_CNV_TestRuns/CNV_Job_Output/dna1802266b/' --filter-unmapped-reads --nr-of-threads '16' --sorting-order 'coordinate' --filter-non-overlapping-reads '/opt/NGS/References/hg19/BedFiles/WGS.bed'`

I also noted that the 'replace reference sequences' option also discarded reads not present in the provided reference sequences (in my case, all the random contigs). So it's good to know that I don't need the 'filter-non-overlapping' with a 'canonical chromosomes' WGS BED file.

**Comment by pcostanza** [comment]
OK, then we know what the problem is. We will try to fix this ASAP.

**Comment by pcostanza** [comment]
We have just released elPrep version 4.1.1 which should fix your problem. Could you try your original call again? That is, a single elprep sfm call with the --replace-reference-sequences and the other options combined, and let us know if that worked?

Thanks a lot,
Pascal

**Comment by geertvandeweyer** [comment]
I ran the test using 4.1.1 and it worked flawlessly. 

Thanks for the fix and sorry for the late reply

**Comment by pcostanza** [comment]
Thanks a lot indeed for verifying our bug fix.
