### ISSUE TITLE
testing?

### ISSUE THREAD

**Issue by kortschak** [ExaScience/elprep#20]
There only a very light covering of the code base with tests here. In my experience, ensuring a safe and robust implementation of BGZF and BAM (and to a lesser degree SAM) is non-trivial. So more tests are certainly warranted.

**Comment by pcostanza** [comment]
Please use GitHub issues only for reporting concrete issues and problems you are having with the software. For general discussions, the Google forum at 
https://groups.google.com/forum/m/#!forum/elprep is more appropriate.

**Comment by kortschak** [comment]
Absence of test coverage is a concrete issue.
