### ISSUE TITLE
BaseRecalibrator maxCycle

### ISSUE THREAD

**Issue by ChristopheH** [ExaScience/elprep#23]
Hello,

I was in JOBM2019 conference, and I have seen the presentation of your elprep4 tool and it looks pretty cool. I decided to test it on our data (PGM sequencing).
Unfortunately I have an issue I had with GATK base recalibrator about the number of cycle :

> 2019/07/11 14:11:09 cycle value exceeds maximum cycle value

In GATK there is an option "-maxCycle" that allow to avoid this error by increasing the default (500 by memory). I believe there is no such option in elprep. Am I wrong ?

Do you have any advice regarding my issue please ?

Thank you for your guidance.

**Comment by pcostanza** [comment]
Apologies for the late reply, but we are only today back from our vacation. We will look into this as soon as possible.

**Comment by pcostanza** [comment]
We have added a --max-cycle option in version 4.1.5 of elPrep. The binary for that version should be available soon. Thanks a lot for reporting this issue. Please let us know if this feature doesn't work for you.
