### ISSUE TITLE
Compilation problems

### ISSUE THREAD

**Issue by bvalot** [ExaScience/elprep#25]
Hi,

When I tried to install your tools, I get the following error:
`$ go get github.com/exascience/elprep`
package github.com/exascience/elprep/v4/cmd: cannot find package "github.com/exascience/elprep/v4/cmd" in any of:
        /usr/lib/go-1.7/src/github.com/exascience/elprep/v4/cmd (from $GOROOT)
        /home/bvalot3/.go/src/github.com/exascience/elprep/v4/cmd (from $GOPATH

The GOPATH variable is set correctly:
`$ echo $GOPATH`
/home/bvalot3/.go

My configuration is:
- Debian Strech
- go version go1.7.4 linux/amd64

Thanks in advance

**Comment by pcostanza** [comment]
Your Go compiler is too old. Go has recently introduced modules to better handle versioning of libraries, and we are using this in elPrep. Please update to a recent version of the Go compiler, and the error message should disappear.
