### ISSUE TITLE
Q: support for PacBio "native" format

### ISSUE THREAD

**Issue by ptrebert** [ExaScience/elprep#27]
Hi,
is elPrep also a drop-in replacement for processing BAM files in "PacBio native" format, i.e., BAM files containing unaligned long reads plus additional quality information that is used for downstream steps such as alignment with `pbmm2`?
Thanks for the info.
+Peter

**Comment by pcostanza** [comment]
Hi,

Unfortunately, I don't believe this will work. elPrep supports the steps in between alignment and variant calling (sorting, marking duplicates, BQSR, etc.) of a typical GATK best-practices pipeline, and they require already aligned BAM files. If you can align the PacBio reads first, it may be possible to use elPrep afterwards, and we have heard other people using elPrep in that way. However, we don't do any testing with long reads ourselves yet, so we cannot guarantee that it will work as expected.

If you want to discuss this in more detail, please let us know.

Cheers,
Pascal

**Comment by ptrebert** [comment]
Hi Pascal,
thanks for the info. Depending on where the future development of elPrep is going, please consider this a feature request. My main reason for asking was that current tools that handle these unaligned/PacBio "native" BAM files seem to be quite slow for tasks such as merging sub-parts into a larger file, or dumping from BAM to FASTQ/FASTA; things that I assume to be rather I/O limited, but that seem to be CPU limited in current implementations, ergo something elPrep could do wonders about. Anyway, I am closing this now. If, at some point, elPrep does support these PacBio BAM files, please announce it loud and clear.
Best,
Peter
