### ISSUE TITLE
elprep sfm mode exits with out of Memory error

### ISSUE THREAD

**Issue by ajayrv** [ExaScience/elprep#30]
Thanks for the great work with elPrep! It has been really useful in cutting down analysis runtimes!

We have been running elPrep (4.1.5) on a WGS dataset to primarily use the mark duplicates and bqsr functionalities, with mixed success. A subset of samples work as expected while some are exiting with the following runtime out of memory error. Would greatly appreciate any inputs regarding this problem - 

```
fatal error: runtime: out of memory

runtime stack:
runtime.throw(0x5f0611, 0x16)
        /opt/local/lib/go/src/runtime/panic.go:617 +0x72
runtime.sysMap(0x11748000000, 0x4000000, 0x78c078)
        /opt/local/lib/go/src/runtime/mem_linux.go:170 +0xc7
runtime.(*mheap).sysAlloc(0x7746c0, 0x2000, 0x7746d0, 0x1)
        /opt/local/lib/go/src/runtime/malloc.go:633 +0x1cd
runtime.(*mheap).grow(0x7746c0, 0x1, 0x0)
        /opt/local/lib/go/src/runtime/mheap.go:1222 +0x42
runtime.(*mheap).allocSpanLocked(0x7746c0, 0x1, 0x78c088, 0x7f9d8df1a888)
        /opt/local/lib/go/src/runtime/mheap.go:1150 +0x37f
runtime.(*mheap).alloc_m(0x7746c0, 0x1, 0x45002f, 0x7f9d8df1a888)
        /opt/local/lib/go/src/runtime/mheap.go:977 +0xc2
runtime.(*mheap).alloc.func1()
        /opt/local/lib/go/src/runtime/mheap.go:1048 +0x4c
runtime.systemstack(0x0)
        /opt/local/lib/go/src/runtime/asm_amd64.s:351 +0x66
runtime.mstart()
        /opt/local/lib/go/src/runtime/proc.go:1153
```

The targeted coverage for the dataset is 60X , the input BAM is roughly ~114GB. The command line taken from the logs - 

`/home/ubuntu/elPrep/elprep sfm INPUTBAM OUTPUTBAM --mark-duplicates --mark-optical-duplicates OUTPUTDUPMETRICS --sorting-order keep --bqsr OUTPUTRECAL --bqsr-reference ucsc.hg19.elfasta --known-sites <knownSiteFiles>`

**Comment by caherzee** [comment]
Hi,

Can you tell us how much RAM your server has? Thanks.

**Comment by ajayrv** [comment]
`              total        used        free      shared  buff/cache   available
Mem:           373G        721M        188G        940K        184G        369G
Swap:            0B          0B          0B`

**Comment by caherzee** [comment]
A problem may be that there is a particular chromosomal region which has an unusually high number of reads mapped to it. We can check this by splitting the bam file by chromosome (contig size 1) and listing the size of the split files that are created this way.

For example:

caherzee@box:/scratch/caherzee/demo$ elprep split NA12878.exome.hg19.bam ./test/ --contig-group-size 1
caherzee@box:/scratch/caherzee/demo$ cd test/
caherzee@box:/scratch/caherzee/demo/test$ ls
NA12878.exome.hg19-spread.bam  splits
caherzee@box:/scratch/caherzee/demo/test$ du -hs NA12878.exome.hg19-spread.bam 
17M     NA12878.exome.hg19-spread.bam
caherzee@box:/scratch/caherzee/demo/test$ du -hs ./splits/*
...

Another problem may be that there is an unusual high number of chimeric reads. We can see that with the above size listing too.

(Testing this may take a while for your WGS sample)

Thanks!

**Comment by ajayrv** [comment]
I had previously split the BAMs by contigs to try running them serially. I do see a few groups that do have a high number of reads mapped to them . For instance from my set, the two groups containing the largest set of reads mapped to them are here - 

7.8G	splits/SAMPLE1.forProcessing-group2.bam
20G	splits/SAMPLE1.forProcessing-group3.bam

The sfm command error posted earlier failed to process the group3 BAM. I also tried processing that BAM alone using the filter mode. Trying to process just the group3 BAM using filter mode with no other jobs on the server also resulted in the same runtime out of memory error.

Is there a workaround to this/ any additional data that you'd like that I can share?

**Comment by caherzee** [comment]
20GB for group 3 is larger than usual. Based on previous experiences, I would have expected around 330GB RAM would be needed, but it seems to go beyond this. It is hard to tell why that is  without looking at the data. Can you tell anything about what sort of data you are running?

Thanks.

**Comment by ajayrv** [comment]
Sure, let me know if you need further specifics -

The data is Whole Genome sequencing data from Human Insulinoma specimens, sequenced on Illumina Novaseq (S4 flowcell, target depth 60X, KAPA HyperPlus WGS used for library prep). The BAMs to be processed with elprep were created by mapping the above data to UCSC GRCh37/hg19 reference genome using BWA.

**Comment by caherzee** [comment]
Since this is tumor data, it is possible that there are regions with unusual high numbers of reads. The reads themselves may also be unusual in the sense that they rapidly build up the data stored in some of the internal data structures used by the algorithms for BQSR or duplicate marking. That is however difficult to figure out without access to a data sample.

An interesting test may be to run a pipeline with that region 3 as input that executes a simple elPrep command (like elprep in.bam out.bam) and/or to run a pipeline that only performs sorting, and see if the run succeeds for those.

Do you have access to a machine with more RAM? If so, it could be interesting to see how much RAM the run would require overall. 

Thanks!

**Comment by ajayrv** [comment]
Running a simple elprep filter <in.bam> <out.bam> with region 3 seems to work ok. Here is a snippet from the logs. 

`
elprep version 4.1.5 compiled with go1.12.7 - see http://github.com/exascience/elprep for more information.

2020/04/28 15:39:30 Created log file at /home/ubuntu/logs/elprep/elprep-2020-04-28-15-39-30-UTC.log
2020/04/28 15:39:30 Command line: [/home/ubuntu/elPrep/elprep filter SAMPLE1.forProcessing-group3.bam SAMPLE1.forProcessing-group3.processed.bam]
2020/04/28 15:39:30 Executing command:
 /home/ubuntu/elPrep/elprep filter SAMPLE1.forProcessing-group3.bam SAMPLE1.forProcessing-group3.processed.bam --sorting-order keep`

Regarding access to the data sample, we will be able to share the sample to look more closely at this error. Is charlotte.herzeel@imec.be a good email address to discuss further regarding the data share?

Thanks!

**Comment by caherzee** [comment]
Yes, you can contact me on that address. Thanks.
