### ISSUE TITLE
filter mismatches and or percentage identity?

### ISSUE THREAD

**Issue by colindaven** [ExaScience/elprep#32]
Hello,

thanks for a really fast and efficient tool.

I know this is primarily targeted towards speeding up preprocessing before the GATK workflow, but I wonder if you had considered mismatches ?

It's actually not that easy to filter by mismatches, especially dynamically. With bamtools you can set a filter as json, eg NM<4, but you can't do this dynamically per read to my knowledge. That leaves pysam, which is slow and an additional dependency.

With long reads eg ONT, it would be very advantageous to set a read filter defined as percent identity or NM per 100 / 1000 bp. This would help to better filter out poor reads, which at the moment are not easy to filter. Some aligners (ngmlr) include a pc identity filter, yet the fastest tools such as minimap2 do not support a percent identity filter.

Are there any plans to add new features like this ?

cheers,
Colin

**Comment by pcostanza** [comment]
Hi,

We currently don't have plans to implement such a filter. We would have to investigate exactly what kinds of semantics are needed, come up with test cases, compare to existing tools, etc., which costs a lot of effort and time. If you are interested to support such an effort, please let us know, and we can discuss this.

However, if this is a fairly simple filter, which it might be based on your description, you could also consider implementing it yourself. Go is quite a straightforward language, and basic filters are quite easy to integrate in our framework. Check out the file filters/simple-filters.go and there, for example, RemoveNonExactMappingReadsStrict as an example of a filter that removes reads based on some tags. You would then also have to ensure that it is recognized in the main filter command - see file cmd/filter.go.

We are very open to accept pull requests once you have something working.

I hope this helps.

Best,
Pascal
