### ISSUE TITLE
Does the command remove duplicates also does the marking of the duplicates?

### ISSUE THREAD

**Issue by babicjovana** [ExaScience/elprep#34]
Hi,
Should command --remove-duplicates only  be used  in combination with --mark-duplicates? Does it also mark the duplicates or just removes previously marked ones? 
(when I used both --mark-duplicates and --remove-duplicates it seamed i got smaller size output file comparing to the one I got with only --remove-duplicates filter)
Thank you.

**Comment by pcostanza** [comment]
The --remove-duplicates option only removes duplicates based on the FLAG entry for each read. It does not trigger marking duplicates. If you also need to mark duplicates, you have to use both --mark-duplicates and --remove-duplicates. (elPrep ensures that they are executed in the correct order.)

I hope this helps.

Best,
Pascal

**Comment by babicjovana** [comment]
Thank you, this was very helpful. 
If I can make a suggestion: you can put that info in the description.
Kindest regards,
