### ISSUE TITLE
Unclipped position not present in SAM alignment 

### ISSUE THREAD

**Issue by babicjovana** [ExaScience/elprep#35]
Hi,
I'm getting failed tasks when using --mark-optical-duplicates, and a message 'Unclipped position not present in SAM alignment'. Could this be the cause, or should I look for some other reason that the task is failing?

Thank you.

**Comment by pcostanza** [comment]
This is potentially a bug in elPrep. Could you show us the full command line how you call elPrep? This would help us identifying the cause of the problem.

Thank you

**Comment by babicjovana** [comment]
elprep sfm C835.HCC1143.2.bam HCC1143.filtered.bam --mark-duplicates --mark-optical-duplicates Metrics.txt

ps.  With some other .bam file everything worked fine, task passed and i also got Metrics file, but for a few others same message and failed tasks.

**Comment by pcostanza** [comment]
Is it possible that the input already has reads with the duplicate flag set? An easy way to find out is to call: 
```
samtools flagstat C835.HCC1143.2.bam
```
If the output reports that there are duplicates in this file, then this could be the problem.

**Comment by babicjovana** [comment]
Hi,

I checked and i turns out the are duplicates present. So does that means if the input file already has some duplicates marked, before elprep filtering that the --mark-optical-duplicates will produce an error?

**Comment by pcostanza** [comment]
Yes, that what it means. This is a bug in elPrep that we haven't seen before. We are going to fix this. We will hopefully have a fix soon.

**Comment by pcostanza** [comment]
We have just released a new version (4.1.6) that should fix this issue. Could you test this and let us know if this works fine now?

**Comment by babicjovana** [comment]
Thank you very much for a prompt reply and fix.
Tasks are no longer failing with input files that have duplicates marked, and everything seems to be working fine.
If anything else comes up I will let you know.

**Comment by pcostanza** [comment]
I'm happy that this resolved your issue. We would like to understand a bit better what you are working on. Do you mind providing a bit of background about your work? Feel free to contact us at exascience@imec.be if you don't want to discuss this in public.
