### ISSUE TITLE
More memory needed than samtools on 1CPU

### ISSUE THREAD

**Issue by Juke34** [ExaScience/elprep#41]
I was trying to sot a huge file, I didn't succeed with elprep (I tried with different combination of CPU even 1). I went back to samtools and succeeded (on 1 CPU). Did you get any similar feedback that elprer is using more memory than sametools in some cases?

**Comment by caherzee** [comment]
Hi,

Can you tell us what the size of the input file is?

How much RAM does your machine have available?

Are you using the elprep filter or elprep sfm mode? The elprep filter mode attempts to load all data into RAM. The sfm mode splits the data by chromosomal regions on disk and operates on those regions one by one, greatly reducing the RAM use.

We have done a comparison of a previous version of elPrep with SAMtools and other tools in one of our papers:
https://journals.plos.org/plosone/article?id=10.1371/journal.pone.0132868 
In those benchmarks, elPrep used less RAM than SAMtools for sorting, but this was an execution with multiple threads. SAMtools sort also operates on disk when data does not fit into memory, a feature elPrep currently does not support. 

Thanks!

**Comment by Juke34** [comment]
file: ~100 million reads (6Go)
The machine I made the try was 250 Go Ram 
The command I used: elprep sfm bam_file --sorting-order coordinate --nr-of-threads 1

`SAMtools sort also operates on disk when data does not fit into memory` that might explain it.

Thank you for the quick

**Comment by caherzee** [comment]
elPrep handles 100+GB bam files in less than 200GB RAM, executing a full variant calling pipeline, so I do not  understand that it runs out of memory on a 250GB RAM server for processing a 6GB bam. From our experience, it should take maybe 24GB of RAM...

What reference are you using? Does the header contain more than one region? (Though even then I would expect this file size to run without problems...)

Do you have an error log for elprep crashing on this sample?

Thanks!
