### ISSUE TITLE
Is this a reasonable way to limit default threads used

### ISSUE THREAD

**Issue by jbh-cas** [ExaScience/elprep#42]
We are very excited to try the new features in Version 5. Version 4 has saved us much time and complexity.

I know that by default GOMAXPROCS is set to all threads. This doesn't work well with our shared system. We have had people use a shell script to force a smaller default. However I was curious if the following change would work for the executable itself. I realize that duplicating the 16 is not the best software hygiene (should be a const var that could be changed just once) but this is an easy change for me to make:
```
cmd/filter.go:	flags.IntVar(&nrOfThreads, "nr-of-threads", 16, "number of worker threads")
cmd/merge.go:	flags.IntVar(&nrOfThreads, "nr-of-threads", 16, "number of worker threads")
cmd/merge-optical-duplicates-metrics.go:	flags.IntVar(&nrOfThreads, "nr-of-threads", 16, "number of worker threads")
cmd/sfm.go:	flags.IntVar(&nrOfThreads, "nr-of-threads", 16, "number of worker threads")
cmd/split.go:	flags.IntVar(&nrOfThreads, "nr-of-threads", 16, "number of worker threads")
```

best and thanks for this utility,

Jim Henderson, Cal Academy of Sciences

**Comment by caherzee** [comment]
Hi,
I am not sure I understand the question. We have the option --nr-of-threads to change the number of threads that the elprep command uses. Is there a problem using this option? E.g. "elprep sfm in.bam out.bam --nr-of-threads 16" would work?

Thanks for testing elPrep!

**Comment by pcostanza** [comment]
@jbh-cas Yes, this would be a way to change the default directly in the elPrep binary. However, this would mean extra effort for you to ensure that your version of elPrep remains in sync with whatever bug fixes and feature enhancements we are going to release in the future. You may also want to look at other means to have a different default number of threads in your shared system, for example by using the Linux ulimit command.

**Comment by jbh-cas** [comment]
Pascal,
Thank you for the quick response. We have a couple of systems that share a common NAS for our data and often the researchers don't realize the thread greediness of particular programs, so we try to limit what they can do on a program by program basis. I'm not the sysadmin so ulimit
is not available for me to set on each of the system's for the researchers. I realize it means redoing the changes each version update. Btw, go 1.16 worked well on the build.
best,
JIm Henderson
---------------------------- Original Message ----------------------------

Subject: Re: [ExaScience/elprep] Is this a reasonable way to limit default threads used (#42)

From: "Pascal Costanza" 

Date: Wed, February 17, 2021 1:55 am

To: "ExaScience/elprep" 

Cc: "Jim Henderson" 

"Mention" 

--------------------------------------------------------------------------




 
@jbh-cas Yes, this
would be a way to change the default directly in the elPrep binary. However, this would mean extra effort for you to ensure that your version of elPrep remains in sync with whatever bug fixes and feature enhancements we are going to release in the future. You may also want to look at other means to
have a different default number of threads in your shared system, for example by using the Linux ulimit command.—
