### ISSUE TITLE
elprep split fails to split into CRAM format

### ISSUE THREAD

**Issue by keithj** [ExaScience/elprep#5]
elPrep version 2.10 (LispWorks pre-compiled distribution)

````
split sam-file /path/to/output/ 
 [--output-prefix name] 
 [--output-type [sam | bam | cram]] 
 [--nr-of-threads nr] 
````

When I select CRAM, I get an error reminding me to specifiy a reference:

````
An error occurred in elPrep 2.10: When creating CRAM output, either a reference-fasta or a reference-fai must be provided.
````

However, when I add the required arguments, elprep complains:

````
elprep split --reference-t Homo_sapiens.GRCh37.NCBI.allchr_MT.fa.fai --output-prefix foo_n --output-type cram --nr-of-threads 12 foo_n.bam  ./elprep/split/
elPrep version 2.10. See http://github.com/exascience/elprep for more information.
Incorrect number of parameters: Expected 2, got 4 (--reference-t Homo_sapiens.GRCh37.NCBI.allchr_MT.fa.fai foo_n.bam ./elprep/split/).
split sam-file /path/to/output/ 
 [--output-prefix name] 
 [--output-type [sam | bam | cram]] 
 [--nr-of-threads nr] 
````

**Comment by caherzee** [comment]
Hi,

This is a bug. The user interface for the split/merge tools did not check for the —reference-t option. The fix (in bucket-sort branch) will be committed to the main branch shortly.

Thanks for reporting the bug.

Charlotte

On 17 Mar 2015, at 13:52, Keith James <notifications@github.com<mailto:notifications@github.com>> wrote:


elPrep version 2.10 (LispWorks pre-compiled distribution)

split sam-file /path/to/output/
 [--output-prefix name]
 [--output-type [sam | bam | cram]]
 [--nr-of-threads nr]


When I select CRAM, I get an error reminding me to specifiy a reference:

An error occurred in elPrep 2.10: When creating CRAM output, either a reference-fasta or a reference-fai must be provided.


However, when I add the required arguments, elprep complains:

elprep split --reference-t Homo_sapiens.GRCh37.NCBI.allchr_MT.fa.fai --output-prefix foo_n --output-type cram --nr-of-threads 12 foo_n.bam  ./elprep/split/
elPrep version 2.10. See http://github.com/exascience/elprep for more information.
Incorrect number of parameters: Expected 2, got 4 (--reference-t Homo_sapiens.GRCh37.NCBI.allchr_MT.fa.fai foo_n.bam ./elprep/split/).
split sam-file /path/to/output/
 [--output-prefix name]
 [--output-type [sam | bam | cram]]
 [--nr-of-threads nr]
