### ISSUE TITLE
Issue during build of v5.1.0

### ISSUE THREAD

**Issue by matthdsm** [ExaScience/elprep#55]
It seems building from source doesn't work:
https://app.circleci.com/pipelines/github/bioconda/bioconda-recipes/53687/workflows/40af8e10-1d30-4541-9fba-0b3cc7ab98c3/jobs/170646

```
13:19:42 BIOCONDA INFO (OUT) go: downloading github.com/exascience/pargo v1.1.0
13:19:42 BIOCONDA INFO (OUT) go: downloading github.com/google/uuid v1.2.0
13:19:42 BIOCONDA INFO (OUT) go: downloading golang.org/x/sys v0.0.0-20210514084401-e8d321eab015
13:19:42 BIOCONDA INFO (OUT) go: downloading github.com/bits-and-blooms/bitset v1.2.0
13:19:44 BIOCONDA INFO (OUT) # github.com/exascience/elprep/v5/sam
13:19:44 BIOCONDA INFO (OUT) sam/split-merge.go:237:21: undefined: MergeInputs
13:19:44 BIOCONDA INFO (OUT) sam/split-merge.go:671:21: undefined: MergeInputs
```

**Comment by matthdsm** [comment]
The latest commits fix the build issue. Can you pin a new release or re-pin the latest release? Then I'll update the conda recipe.

Thanks
M

**Comment by caherzee** [comment]
Done. Thanks!

**Comment by matthdsm** [comment]
Awesome, thank you!
You'll see the new version number pop up in the README tags shortly.
I had already fixed the current version with a patch too.

M
