### ISSUE TITLE
vcf-to-elsites

### ISSUE THREAD

**Issue by Mahmoudbassuoni** [ExaScience/elprep#58]
Hi,  @caherzee 
I am trying to convert a vcf file to elsites but I am getting an error message like this 
`missing ID in a VCF meta-information line: PEDIGREE=<Child=NA12877,Mother=NA12890,Father=NA12889>`
that's the log for the process 
```
elprep version 5.1.1 compiled with go1.16.7 - see http://github.com/exascience/elprep for more information.

2022/01/10 14:00:16 Created log file at ../analysis/elprep_VC/logs/elprep/elprep-2022-01-10-14-00-16-701177358-EET.log
2022/01/10 14:00:16 Command line: [elprep vcf-to-elsites NA12877.vcf NA12877.elsites --log-path ../analysis/elprep_VC/]
2022/01/10 14:00:16 missing ID in a VCF meta-information line: PEDIGREE=<Child=NA12877,Mother=NA12890,Father=NA12889>
panic: missing ID in a VCF meta-information line: PEDIGREE=<Child=NA12877,Mother=NA12890,Father=NA12889>

goroutine 1 [running]:
log.Panicf(0x687f09, 0x2d, 0xc000063b90, 0x1, 0x1)
	/opt/conda/conda-bld/elprep_1633347706013/_build_env/go/src/log/log.go:361 +0xc5
github.com/exascience/elprep/v5/vcf.(*StringScanner).ParseMetaInformation(0xc000063c90, 0xc000022440, 0x36)
	/opt/conda/conda-bld/elprep_1633347706013/work/vcf/vcf-files.go:155 +0x2ed
github.com/exascience/elprep/v5/vcf.ParseHeader(0xc0000104e0, 0x2e, 0xc000074120)
	/opt/conda/conda-bld/elprep_1633347706013/work/vcf/vcf-files.go:293 +0x21b
github.com/exascience/elprep/v5/intervals.FromVcfFile(0x7ffdaa54d41c, 0xb, 0x0)
	/opt/conda/conda-bld/elprep_1633347706013/work/intervals/intervals.go:310 +0xb8
github.com/exascience/elprep/v5/cmd.VcfToElsites()
	/opt/conda/conda-bld/elprep_1633347706013/work/cmd/convert.go:47 +0x228
main.main()
	/opt/conda/conda-bld/elprep_1633347706013/work/main.go:75 +0x38b
```
I am not sure what could be the issue. the VCF file I am using is for the platinum genome from illumina so can anyone help here ?

**Comment by caherzee** [comment]
Hi,

It apprears the vcf file you are trying to convert is not correctly formatted according to the VCF specification.  Is it possible to add the missing header information to your VCF or to use another correctly formatted VCF?

**Comment by Mahmoudbassuoni** [comment]
Hi, 
that's the VCF that was available from illumina for that sample but I can check if I should add that line to the header. but another thing is that I have tried to run the variant calling normally and it happened to be producing a vcf that totally not correct and it doesn't have anything common with the gold standard one. I have already sent this issue to your email if you can check it there. 

Thanks,

**Comment by caherzee** [comment]
Hi,

You need to follow specific instructions to be able to do a one to one comparison between elPrep and other tools outputs. Please consult our publications, cf. https://journals.plos.org/plosone/article?id=10.1371/journal.pone.0244471 and specifically, the supplementary material. elPrep was also validated by Seven Bridges Genomics, which may also be a good place to check.

Thanks,

Charlotte
