### ISSUE TITLE
`elprep split` output directory

### ISSUE THREAD

**Issue by matthdsm** [ExaScience/elprep#62]
Hi,

It seems like `split` doesn't correctly parse the output directory given on the command line
```
$ elprep split input test --nr-of-threads 2 --output-prefix test                                                                             
2022/04/13 09:36:14 Given output path is not a path: test.
```
or 
```
$ elprep split input ./test --nr-of-threads 2 --output-prefix test 
2022/04/13 09:36:22 Given output path is not a path: ./test.
```
or even
```
$ elprep split input $PWD/test --nr-of-threads 2 --output-prefix test 
2022/04/13 09:37:08 Given output path is not a path: /projects/exome/development/elprep/test.
```
```
$ elprep split input /projects/exome/development/elprep/test --nr-of-threads 2 --output-prefix test 
2022/04/13 09:37:08 Given output path is not a path: /projects/exome/development/elprep/test.
```

What does work is
```
$ elprep split input . --nr-of-threads 2 --output-prefix test 
```

The `test` directory does not exist yet, but according to the docs it should be made by `elprep`

Cheers
Matthias

**Comment by matthdsm** [comment]
Apparently, go `filepath` requires a path to end with `/`, causing this issue.

**Comment by matthdsm** [comment]
Yes, it did. But since the directory existed, I didn't quite catch the fact at first the output path needed to end with a `/`

**Comment by caherzee** [comment]
Is it ok to keep this error message or do you still consider this an issue?

**Comment by matthdsm** [comment]
I don't mind now that I know whats up 🙂
